### ISSUE TITLE
Is there any way to force this update to the Kodi repository?

### ISSUE THREAD

**Issue by pim013** [putdotio/putio-kodi#14]
I'm sorry to ask this question here but Kodi doesn't provide an answer in their FAQ/Help section. I need the put.io version updated for Kodi v19 but it isn't visible on the addon repository yet.
Can I force it somehow?

**Comment by BatuAksoy** [comment]
Hey @pim013,
We sent this add-on to official kodi plugins repo and it is accepted. See here: https://github.com/xbmc/repo-plugins/pull/3428

It will take a little more time to see it in kodi. Because kodi only pulls them in a specific period.

Meanwhile if you want to use it, you can sideload it. To do so, you can follow these steps:
- Go to Settings > System > Add-ons and Enable **Unknown Sources** option.
- Download this repository as zip. (Or simply click here: https://github.com/putdotio/putio-kodi/archive/master.zip)
- Go to Home > Add-ons > Install from zip file
- Find zip you previously downloaded

When it is pulled by kodi, you can uninstall sideloaded version and install official version. Or you can continue to use it.
Hope this helps, cheers!
